spring:
  cloud:
    gateway:
      routes:
        - id: test-route
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu

        - id: qq-test
          uri: http://www.qq.com
          predicates:
            - Query=url,qq

        - id: admin-third
          uri: lb://recruitment-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}

        - id: admin-employee
          uri: lb://employee
          predicates:
            - Path=/api/employee/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin-company
          uri: lb://company
          predicates:
            - Path=/api/company/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin-route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}

